type Character = {
  name: string;
  tags: string[];
};

const characters: Character[] = [
  { name: "D_Man", tags: [] },
  { name: "Eagle", tags: [] },
  { name: "Blastoise", tags: ["pokemon", "Video game"] },
  { name: "PrincePlanet", tags: [] },
  { name: "Impulse", tags: [] },
  { name: "BlackWidow", tags: [] },
  { name: "Kif", tags: [] },
  { name: "Pearl", tags: [] },
  { name: "Vampirella", tags: [] },
  { name: "RiffRaff", tags: [] },
  { name: "Rex", tags: [] },
  { name: "Maruka", tags: [] },
  { name: "Haku", tags: [] },
  { name: "Dooly", tags: [] },
  { name: "Gordon_Freeman", tags: ["Video game"] },
  { name: "Bobby", tags: [] },
  { name: "TARDIS", tags: ["TV"] },
  { name: "Spunky", tags: [] },
  { name: "Johnny_Test", tags: [] },
  { name: "Ash_Ketchum", tags: ["pokemon", "Video game"] },
  { name: "Sharky", tags: [] },
  { name: "Porkchop", tags: [] },
  { name: "Little_Prince", tags: [] },
  { name: "Venusaur", tags: ["pokemon", "Video game"] },
  { name: "Baymax", tags: [] },
  { name: "Cindy_Loo_Who", tags: [] },
  { name: "Sora", tags: ["Video game"] },
  { name: "Vision", tags: ["Comic"] },
  { name: "The_General", tags: [] },
  { name: "The_Impossibles", tags: [] },
  { name: "Planes", tags: [] },
  { name: "Salem", tags: [] },
  { name: "Alice", tags: ["Video game"] },
  { name: "Kablam", tags: [] },
  { name: "Mighty_Max", tags: [] },
  { name: "Sabrina", tags: [] },
  { name: "Dalmation", tags: [] },
  { name: "Clyde", tags: [] },
  { name: "Leonardo", tags: ["TV"] },
  { name: "Prometheus", tags: ["TV"] },
  { name: "Bob", tags: [] },
  { name: "Rango", tags: [] },
  { name: "Bill_The_Cat", tags: [] },
  { name: "Opus", tags: [] },
  { name: "ChernaBog", tags: [] },
  { name: "Spyro", tags: ["Video game"] },
  { name: "Venger", tags: [] },
  { name: "Westley", tags: ["Movie"] },
  { name: "Milo", tags: ["TV"] },
  { name: "Uncle_Grandpa", tags: [] },
  { name: "Silver_Hawks", tags: ["TV"] },
  { name: "Kida", tags: [] },
  { name: "Benson", tags: [] },
  { name: "Cerberus", tags: [] },
  { name: "Claptrap", tags: ["Video game"] },
  { name: "Robo", tags: [] },
  { name: "LeChuck", tags: ["Video game"] },
  { name: "SugarBear", tags: [] },
  { name: "Venture_Bros", tags: [] },
  { name: "Crash_Dummies", tags: ["Video game"] },
  { name: "Crocs_By_Suze", tags: [] },
  { name: "Valiant", tags: [] },
  { name: "Lupin", tags: ["Comic"] },
  { name: "Beedrill", tags: ["pokemon", "Video game"] },
  { name: "Weedle", tags: ["pokemon", "Video game"] },
  { name: "Sluggo", tags: ["Comic"] },
  { name: "Nancy", tags: ["Comic"] },
  { name: "BattleToads", tags: ["Video game"] },
  { name: "School_House_Rock", tags: ["TV"] },
  { name: "NemesisEnforcer", tags: [] },
  { name: "Condorito", tags: ["TV"] },
  { name: "Bravestar", tags: ["TV"] },
  { name: "Rom", tags: [] },
  { name: "Dungeons_And_Dragons", tags: ["TV"] },
  { name: "Gasoline_Alley", tags: [] },
  { name: "Twayne", tags: [] },
  { name: "Dalmation", tags: [] },
  { name: "Hippety", tags: [] },
  { name: "Widget", tags: [] },
  { name: "Goblin_King", tags: ["Movie"] },
  { name: "Sophie", tags: [] },
  { name: "Lara_Croft", tags: ["Video game"] },
  { name: "Susan", tags: [] },
  { name: "Mary", tags: [] },
  { name: "Donny", tags: [] },
  { name: "Claus", tags: ["TV"] },
  { name: "Toot", tags: [] },
  { name: "CaptainCanuck", tags: [] },
  { name: "Dog_?", tags: [] },
  { name: "Sneezy", tags: [] },
  { name: "Sid", tags: ["Movie"] },
  { name: "Frankenweenie", tags: ["Movie"] },
  { name: "Snork", tags: [] },
  { name: "Dukie", tags: ["TV"] },
  { name: "GForce", tags: [] },
  { name: "James_Bond", tags: ["Video game"] },
  { name: "Rio", tags: [] },
  { name: "Duck_Hunt", tags: ["Video game"] },
  { name: "Sinestro", tags: [] },
  { name: "Pikachu", tags: ["pokemon", "Video game"] },
  { name: "Vector1", tags: [] },
  { name: "Telebugs", tags: [] },
  { name: "Weasel", tags: [] },
];

export const uniqueCharacters = characters.map(char => char.name);
export { characters };